# Generated by Django 5.1.5 on 2025-01-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userrefreshtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrefreshtoken',
            name='refresh_token',
            field=models.CharField(editable=False, max_length=512, unique=True),
        ),
    ]
